QUERY_GENERATION_PROMPT = (
    "Given a search query or claim, generate exactly 3 YouTube search queries to "
    "surface videos covering different perspectives on the topic: "
    "1) a query finding videos that support or argue for the claim, "
    "2) a query finding videos that oppose, criticise, or debunk the claim, "
    "3) a neutral debate or analysis framing of the same topic. "
    "For example, if the query is 'AI is beneficial for humanity', the queries should be: "
    "1) 'AI is beneficial for humanity' "
    "2) 'AI is harmful for humanity' "
    "3) 'AI is neutral on the topic of humanity' "
    "Another example where the query may be more ambiguous, such as 'Israel'"
    "the queries should be: "
    "1) 'Israel' "
    "2) 'Israel is a terrorist state' "
    "3) 'Israel is a peaceful country' "
    "Return a JSON array of exactly 3 short search strings. Return only valid JSON."
)

VIDEO_STANCE_PROMPT = (
    "You are classifying the overall stance of YouTube videos toward a given topic. "
    "For each video, infer stance from the provided title, description, and transcript text only "
    "(if available). Do not use outside knowledge. "
    "Assign exactly one stance label per video: "
    "-1 = Against/opposing the topic or claim, "
    "0 = Neutral/ambiguous/mixed/no clear position, "
    "1 = In favour/supporting the topic or claim. "
    "Decision rules: "
    "1) Prioritise the dominant message of the video, not isolated quotes. "
    "2) If the video presents multiple sides without endorsing one, use 0. "
    "3) If criticism is aimed at implementation details while still supporting the core claim, use 1. "
    "4) If support is weak/uncertain and evidence is balanced or unclear, use 0. "
    "5) If the video primarily argues the claim is false/harmful/wrong, use -1. "
    "6) If content is unrelated to the topic, use 0. "
    "Calibration examples (topic: 'AI is beneficial for humanity'): "
    "'AI will transform medicine and education for the better; this is a net positive.' -> stance=1. "
    "'AI progress is dangerous and will harm society unless stopped.' -> stance=-1. "
    "'Experts debate AI risks and benefits with no clear conclusion.' -> stance=0. "
    "Return a JSON array where each element has: id (string), stance (-1/0/1). "
    "Return only valid JSON, with no extra text."
)
